services:
  db:
    image: postgres:15-alpine
    container_name: worldscars-db
    environment:
      POSTGRES_DB: worldscars
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - worldscars-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: worldscars-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - worldscars-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: worldscars-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - worldscars-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  worldscars-network:
    driver: bridge
